### ISSUE TITLE
Add Args, Command and Secret support when creating ACI container through aci-connector

### ISSUE THREAD

**Issue by zackliu** [Azure/aci-connector-k8s#18]
I defined a pod with `command` and `args` in yaml. When I run `az container show` in Azure CLI, it showed `"command"= null`.
At the same time, `ImagePullSecret` doesn't work as well.

I know this project is in a preview stage, but `args`, `command` and `secret` are very critical features. So I want to know do we have a roadmap to support these features.

**Comment by yaron2** [comment]
Hi @zackliu ,

See me PR #27 for command and environment variable support.

Secrets and Args are not yet supported by Azure Container Instances so there is currently no way to enable that functionality.

**Comment by lachie83** [comment]
ImagePullSecrets will be handled in #37 . Generic Kubernetes secrets are not currently supported.

**Comment by lachie83** [comment]
These are all now supported.

**Comment by Kamshak** [comment]
@lachie83 in the README (https://github.com/Azure/aci-connector-k8s#limitations) it says that secrets are not supported, is this still up to date?
