### ISSUE TITLE
Service does not get an external IP

### ISSUE THREAD

**Issue by seglauf** [Azure/aci-connector-k8s#30]
1. I did the Tutorial from https://docs.microsoft.com/de-de/azure/container-service/kubernetes/container-service-tutorial-kubernetes-deploy-application
--> everyting was fine

2. Deployed ACI as descripbed on https://github.com/Azure/aci-connector-k8s#using-the-kubernetes-scheduler

3. Tried to repete 1. withot any changes.
--> Service will no longer get a external IP. It stays in state pending for ever.

Any Idee what i did wrong?

**Comment by ThorstenHans** [comment]
@seglauf do you have registered `Microsoft.ContainerInstance` for your subscription? 

you can verify it by executing 

```
$ az provider show -n Microsoft.ContainerInstance
```

I guess it'll say `NotRegistered`. If so, go and execute 

```
$ az provider register -n Microsoft.ContainerInstance
```
After a couple of seconds `az provider show -n Microsoft.ContainerInstance` should say `Registered` and then you should be able to create the `LoadBalancer`

**Comment by seglauf** [comment]
Yes i dos that
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.08.17, 08:41, Thorsten Hans <notifications@github.com> schrieb:
@seglauf do you have registered Microsoft.ContainerInstance for your subscription?
you can verify it by executing
$ az provider show -n Microsoft.ContainerInstance

I guess it'll say NotRegistered. If so, go and execute
$ az provider register -n Microsoft.ContainerInstance

After a couple of seconds az provider show -n Microsoft.ContainerInstance should say Registered and then you should be able to create the LoadBalancer

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azure/aci-connector-k8s","title":"Azure/aci-connector-k8s","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azure/aci-connector-k8s"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ThorstenHans in #30: @seglauf do you have registered `Microsoft.ContainerInstance` for your subscription? \r\n\r\nyou can verify it by executing \r\n\r\n```\r\n$ az provider show -n Microsoft.ContainerInstance\r\n```\r\n\r\nI guess it'll say `NotRegistered`. If so, go and execute \r\n\r\n```\r\n$ az provider register -n Microsoft.ContainerInstance\r\n```\r\nAfter a couple of seconds `az provider show -n Microsoft.ContainerInstance` should say `Registered` and then you should be able to create the `LoadBalancer`"}],"action":{"name":"View Issue","url":"https://github.com/Azure/aci-connector-k8s/issues/30#issuecomment-324547695"}}}

**Comment by seglauf** [comment]
Provider Microsoft.ContainerInstance was registered.

**Comment by lachie83** [comment]
Hi @seglauf sometimes the Azure LB provisioner takes some time to receive an IP address which is why you see things in pending state. If you using kubectl to describe the svc you should see the event log of what the provisioner is doing.

**Comment by seglauf** [comment]
Tests have shown that it was not ok even after 2 hours.

 

Von: Lachlan Evenson [mailto:notifications@github.com] 
Gesendet: Freitag, 25. August 2017 00:33
An: Azure/aci-connector-k8s <aci-connector-k8s@noreply.github.com>
Cc: seglauf <seglauf@gmx.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [Azure/aci-connector-k8s] Service does not get an external IP (#30)

 

Hi @seglauf <https://github.com/seglauf>  sometimes the Azure LB provisioner takes some time to receive an IP address which is why you see things in pending state. If you using kubectl to describe the svc you should see the event log of what the provisioner is doing.

**Comment by rbitia** [comment]
Hi @seglauf I've reproduced this issue - try deleting the cluster and provisioning the service principle under your subscription instead of the resource group:
az ad sp create-for-rbac --role=Contributor --scopes /subscriptions/<subscriptionId>

**Comment by rbitia** [comment]
Closing issue now that the readme is updated
