### ISSUE TITLE
Microsoft.ContainerInstance provider not registered

### ISSUE THREAD

**Issue by frederimandin** [Azure/aci-connector-k8s#33]
When I have tried to start my first pod onto the aci-connector, it kept waiting in 'creating' status. I've found in Azure Portal Activity log an error like this one

> Operation name : Write ContainerGroups
> Time stamp : Thu Aug 24 2017 15:31:58 GMT+0200 (Paris, Madrid (heure d’été))
> Event initiated by : azure-cli-2017-08-24-13-01-33
> Error code : MissingSubscriptionRegistration
> Message : The subscription is not registered to use namespace 'Microsoft.ContainerInstance'. See https://aka.ms/rps-not-found for how to register subscriptions.

I just solved that by registering the provider 
```
az provider list -o table | grep ContainerInstance
az provider register -n Microsoft.ContainerInstance
```
After that everything ran smoothly.

**Comment by lachie83** [comment]
@frederimandin Thank you. I'll get this added to the documentation
