### ISSUE TITLE
Tried aci-connector on K8s on Azure, GKE, and private k8s = NO DICE

### ISSUE THREAD

**Issue by JockDaRock** [Azure/aci-connector-k8s#40]
Have not been able to successfully been able to deploy the ACI connector example.

I follow the instructions on the README.md exactly and the sample NGINX app is permanently stuck in the pending state.

Any help here would be appreciated.

I currently have it running in Azure and it is currently stuck in pending for the example nginx app.

**Comment by seglauf** [comment]
do you have registered Microsoft.ContainerInstance for your subscription?
you can verify it by executing
$ az provider show -n Microsoft.ContainerInstance
I guess it'll say NotRegistered. If so, go and execute
$ az provider register -n Microsoft.ContainerInstance
After a couple of seconds az provider show -n Microsoft.ContainerInstance should say Registered and then you should be able to create the LoadBalancer

**Comment by JockDaRock** [comment]
I thought I did, but I have not verified that. Will give it a shot and let you know.

**Comment by JockDaRock** [comment]
this worked.  I am good now, thank you for updating the docs. This issue can be closed now.

**Comment by rbitia** [comment]
Thanks for the input! Glad it worked - closing issue
