### ISSUE TITLE
How to create Deployment using ACI for Windows Container from K8S?

### ISSUE THREAD

**Issue by doggy8088** [Azure/aci-connector-k8s#72]
I'd like to create a Deployment from my ACS for K8S using `aci-connection-k8s`.  How can I config osType in the Deployment YAML file? 

The aci-connector looks like hard-coded osType to "linux" at this time.   Is there any plan on supporting ACI for Windows Container?

**Comment by kkmsft** [comment]
I believe there is a PR for this, which is the review backlog: https://github.com/Azure/aci-connector-k8s/pull/25

**Comment by rbitia** [comment]
hi! please use the microsoft/aci-connector-k8s:canary to get windows support! Thanks

**Comment by rbitia** [comment]
If there's no follow up I'll close the issue :)
